/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regform;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author BOSS
 */
public class editstd extends javax.swing.JFrame {

    static void print(JTable.PrintMode printMode, MessageFormat header, MessageFormat footer) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    Connection conn= null;
    PreparedStatement stmt= null;
    /**
     * Creates new form editstd
     */
    public editstd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fname1 = new javax.swing.JTextField();
        surname1 = new javax.swing.JTextField();
        username1 = new javax.swing.JTextField();
        sex1 = new javax.swing.JComboBox<>();
        dob1 = new javax.swing.JTextField();
        pob1 = new javax.swing.JTextField();
        division1 = new javax.swing.JTextField();
        pname1 = new javax.swing.JTextField();
        padd1 = new javax.swing.JTextField();
        nationality1 = new javax.swing.JTextField();
        mstatus1 = new javax.swing.JComboBox<>();
        password1 = new javax.swing.JTextField();
        region1 = new javax.swing.JComboBox<>();
        edit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sdtid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, 30));
        jPanel1.add(surname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, 30));

        username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username1ActionPerformed(evt);
            }
        });
        jPanel1.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 220, 30));

        sex1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));
        jPanel1.add(sex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 220, 30));

        dob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob1ActionPerformed(evt);
            }
        });
        jPanel1.add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 220, 30));

        pob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pob1ActionPerformed(evt);
            }
        });
        jPanel1.add(pob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 220, 30));
        jPanel1.add(division1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 220, 30));
        jPanel1.add(pname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 220, 30));

        padd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padd1ActionPerformed(evt);
            }
        });
        jPanel1.add(padd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 220, 30));
        jPanel1.add(nationality1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 220, 30));

        mstatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "married", "not married", "others" }));
        jPanel1.add(mstatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 220, 30));
        jPanel1.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 220, 30));

        region1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADAMAWA ", "CENTRE", "EAST", "FAR NORTH", "LITTORAL", "NORTH", "NORTH WEST", "WEST", "SOUTH ", "SOUTH WEST" }));
        jPanel1.add(region1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 220, 30));

        edit.setBackground(new java.awt.Color(0, 255, 0));
        edit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("UPDATE");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, 100, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("EDIT STUDENT REGISTRATION FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 450, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("SURNAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("USERNAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("SEX");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("DATE OF BIRTH");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 255));
        jLabel12.setText("PLACEOFBIRTH");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 255));
        jLabel10.setText("DIVISION ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 255));
        jLabel14.setText("PARENT NAME");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 255));
        jLabel15.setText("PARENT ADDRESS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setText("REGION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setText("NATIONALITY");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("MARITAL STATUS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 255));
        jLabel13.setText("PASSWORD");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setText("ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));
        jPanel1.add(sdtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 220, 30));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 80, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\BOSS\\Documents\\NetBeansProjects\\Regform\\src\\regform\\main.jpg")); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

        String SID = sdtid.getText();
        String fname = fname1.getText();
        String surname = surname1.getText();
        String username = username1.getText();
        String sex = (String) sex1.getSelectedItem();
        String dob = dob1.getText();
        String pob = pob1.getText();
        String division = division1.getText();
        String pname = pname1.getText();
        String padd = padd1.getText();
        String region = (String) region1.getSelectedItem();
        String nationality = nationality1.getText();
        String mstatus = (String) mstatus1.getSelectedItem();
        String password = password1.getText();

        try{

            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/registration_details", "root", "");
            String query = "update user set `username`='"+username+"' ,`sex`='"+sex+"' ,`dob`='"+dob+"' ,`pob`='"+pob+"' ,`division`='"+division+"' ,`pname`='"+pname+"' ,`padd`='"+padd+"' ,`region`='"+region+"' ,`nationality`='"+nationality+"' ,`mstatus`='"+mstatus+"' ,`password`='"+password+"' where `SID`="+SID;

            stmt=conn.prepareStatement(query);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Records have been successfully updated");
            conn.close();

            dashboard c = new  dashboard();
            this.hide();
            c.setVisible(true);

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void padd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_padd1ActionPerformed

    private void pob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pob1ActionPerformed

    private void dob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob1ActionPerformed

    private void username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            dashboard c = new  dashboard();
            this.hide();
            c.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editstd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField division1;
    private javax.swing.JTextField dob1;
    private javax.swing.JButton edit;
    private javax.swing.JTextField fname1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mstatus1;
    private javax.swing.JTextField nationality1;
    private javax.swing.JTextField padd1;
    private javax.swing.JTextField password1;
    private javax.swing.JTextField pname1;
    private javax.swing.JTextField pob1;
    private javax.swing.JComboBox<String> region1;
    private javax.swing.JTextField sdtid;
    private javax.swing.JComboBox<String> sex1;
    private javax.swing.JTextField surname1;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}
